{{ if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-data
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{ end }}