{{- if or (eq .Values.authentication.enabled true) (eq .Values.authorization.enabled true) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.authentication.enabled }}
  passwd.txt:
  {{- range .Values.authentication.users }}
    {{ .name }}:{{ .password }}
  {{- end}}
  {{- end }}
  {{- if .Values.authorization.enabled }}
  mosquitto.aclfile:
  {{- range .Values.authorization.acls }}
    user {{ .user }}
    {{- range .topics }}
    topic {{ .access }} {{ .name }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}